.PHONY: clean requirements

.DEFAULT_GOAL := help


help: ### Display this help message
	@echo "Please use \`make <target>' where <target> is one of"
	@perl -nle'print $& if m{^[a-zA-Z_-]+:.*?## .*$$}' $(MAKEFILE_LIST) | sort | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m  %-25s\033[0m %s\n", $$1, $$2}'

clean: ## Remove generated byte code, coverage reports, and build artifacts
	@echo "--> Clean Python files ..."
	find . -name '__pycache__' -exec rm -rf {} +
	find . -name '*.pyc' -exec rm -f {} +
	find . -name '*.pyo' -exec rm -f {} +
	find . -name '*~' -exec rm -f {} +
	rm -fr build/
	rm -fr dist/
	rm -fr *.egg-info

	@echo "The project has been cleaned successfully."

selfcheck: ## Check that the Makefile is well-formed
	@echo "The Makefile is well-formed."

requirements: ## Installs all requirements needed by development and test environments
	pip install -q -r requirements.txt --exists-action w
	@echo "Finished installing requirements."

styles: ## Compile the project's styles
	npm install
	@echo "Finished installing requirements."

ssh: ## SSH into heroku
	@heroku run bash