# Generated by Django 2.0.1 on 2018-01-11 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahmedjazzarcom', '0006_contactrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='work')),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(db_index=True, max_length=128)),
                ('type', models.CharField(max_length=128)),
                ('short_description', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('services', models.CharField(max_length=512)),
                ('main_image', models.ImageField(upload_to='works')),
                ('link', models.URLField(blank=True, null=True)),
                ('images', models.ManyToManyField(to='ahmedjazzarcom.ImageModel')),
            ],
        ),
    ]
