# Generated by Django 2.0.1 on 2018-01-13 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahmedjazzarcom', '0007_imagemodel_work'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=128)),
                ('text', models.TextField()),
                ('short_description', models.CharField(max_length=160)),
                ('image', models.ImageField(null=True, upload_to='blog')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='requested_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
