# Generated by Django 2.0.1 on 2018-01-13 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ahmedjazzarcom', '0008_auto_20180113_1837'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='ahmedjazzarcom.Blog')),
            ],
        ),
    ]
