# Generated by Django 2.0.1 on 2018-01-13 21:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ahmedjazzarcom', '0009_blogview'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
