# Generated by Django 2.0.1 on 2018-01-13 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahmedjazzarcom', '0010_work_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coffee_cups', models.IntegerField()),
                ('clients', models.IntegerField()),
                ('projects', models.IntegerField()),
                ('hours', models.IntegerField()),
            ],
        ),
    ]
