# Generated by Django 2.0.1 on 2018-01-13 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahmedjazzarcom', '0012_blog_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=128)),
                ('quote', models.CharField(max_length=512)),
                ('image', models.ImageField(upload_to='')),
                ('page', models.CharField(choices=[('about', 'About Me'), ('blog', 'Blog'), ('contact', 'Contact Me'), ('home', 'Home'), ('work', 'Work')], max_length=128)),
                ('center_text', models.BooleanField(default=False)),
                ('classes', models.CharField(default='col-md-6 col-md-offset-3 col-md-pull-3', help_text='col-md-6 col-md-offset-3 col-md-pull-3', max_length=265)),
            ],
        ),
    ]
