# Generated by Django 2.0.1 on 2018-01-15 17:33

from django.db import migrations
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('ahmedjazzarcom', '0015_blog_header_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='text',
            field=martor.models.MartorField(),
        ),
    ]
