# Generated by Django 2.0.1 on 2018-01-15 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahmedjazzarcom', '0016_auto_20180115_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='header_color',
        ),
        migrations.AddField(
            model_name='blog',
            name='related_posts',
            field=models.ManyToManyField(related_name='_blog_related_posts_+', to='ahmedjazzarcom.Blog'),
        ),
    ]
