# Generated by Django 2.0.1 on 2018-01-15 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahmedjazzarcom', '0017_auto_20180115_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='related_works',
            field=models.ManyToManyField(related_name='_work_related_works_+', to='ahmedjazzarcom.Work'),
        ),
    ]
