# Generated by Django 2.0.1 on 2018-01-16 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahmedjazzarcom', '0018_work_related_works'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='order',
            field=models.PositiveSmallIntegerField(null=True, unique=True),
        ),
    ]
