# Generated by Django 2.0.1 on 2018-01-19 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahmedjazzarcom', '0020_auto_20180117_0731'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='pub_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
