# Generated by Django 2.0.1 on 2019-03-22 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahmedjazzarcom', '0024_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='related_posts',
            field=models.ManyToManyField(blank=True, null=True, related_name='_blog_related_posts_+', to='ahmedjazzarcom.Blog'),
        ),
        migrations.AlterField(
            model_name='work',
            name='related_works',
            field=models.ManyToManyField(blank=True, null=True, related_name='_work_related_works_+', to='ahmedjazzarcom.Work'),
        ),
    ]
